# tar -xzf node.tar.gz
#
# Warning use ' for string not " if you want to use deploy.sh
SubAddresses = 'cf-us1.unchainese.com:443,n-us1.unchainese.com:80' # hosts for generate vless URL
AppPort = '80' # websocket server listen address
RegisterUrl = 'https://unchainapi.bob99.workers.dev/api/node' # the master admin server for user auth,data traffic. can be empty if you only want to use the node for yourself
RegisterToken = ''# can be empty string if you only want to use the node for yourself
AllowUsers = '6fe57e3f-e618-4873-ba96-a76adec22ccd,6fe57e3f-e618-4873-ba96-a76adec22cce' # UUID string eg. '6fe57e3f-e618-4873-ba96-a76adec22ccd,6fe57e3f-e618-4873-ba96-a76adec22cce'  can not be empty if you want to use the node for yourself in standalone mode
LogFile = '' # can be empty if you don't want to log to file, so the log will be print to stdout
DebugLevel = 'debug' # debug, info, warn, error
IntervalSecond = '7200'
EnableDataUsageMetering = 'true'
BufferSize = '8192' # buffer size in bytes for WebSocket and TCP/UDP reads